function _write_latex_report(texfile::String, report_title::String, output_figures::Vector{String}, error_figures::Vector{String}, metrics_file::String;
    author::String = "Generated by TLALOQUE Test Suite", intro_extra::String = "")
    ofig = length(output_figures)
    efig = length(error_figures)
    if !isfile(metrics_file)
        @warn "Metrics file not found. The report will be generated without the error metrics."
        metrics = "Metrics file not found. This could be because there is no analytical solution
        or because there is no complete support for this test"
    else
        metrics = read(metrics_file, String)
    end
    open(texfile, "w") do io
        write(io, """
        \\documentclass{article}
        \\usepackage[utf8]{inputenc}
        \\usepackage{amsmath}
        \\usepackage{float}
        \\usepackage{graphicx}
        \\usepackage[margin=0.5in]{geometry}
        \\title{$report_title}
        \\author{$author}
        \\date{\\today}

        \\begin{document}
        
        \\maketitle
        \\section{Introduction}
        This report summarizes the results of the test suite for $report_title and is generated automatically. The test asociated with this report generated $ofig figures
        which correspond to the number of output files generated by the test. All the reports generated by TLALOQUE follow the same structure, first the figures of the output variables
        are shown in the section Test Results, then the error plots and the error global metrics are shown in the section Error Analysis. The error metrics are calculated using the exact 
        solution of the test (when available, when not available a reference numerical solution is used) and the numerical solution obtained from the output files. The error metrics 
        calculated are: The Mean Absolute Percentage Error (MAPE), the Root Mean Square Percentage Error (RMSPE), the \$L_{1}\$ norm, the \$L_{2}\$ norm and the \$L_{\\infty}\$ norm. 
        The error plots show the relative percentage error of each variable as a function of the spatial coordinate (usualy in a diagonal profile of the domain). $intro_extra\\\\
        \\section{Test Results}
            The following figures show the numerical results compared to the exact solutions (when available).\\\\
            """)
        for i in 1:ofig
            write(io, """
            \\begin{figure}[H]
                \\centering
                \\includegraphics[width=0.95\\textwidth]{$(output_figures[i])}
                \\caption{Figure $(i) from the $report_title output.}
            \\end{figure}
            """)
        end
        write(io, """
        \\section{Error Analysis}
        The following figures show the error of the numerical solution compared to the exact solution (when available) as a function of the spatial coordinate. The error metrics 
        calculated are shown in the table below.\\\\
        """)
        for i in 1:efig
            write(io, """
            \\begin{figure}[H]
                \\centering
                \\includegraphics[width=0.95\\textwidth]{$(error_figures[i])}
                \\caption{Figure $(i) from the $report_title error analysis.}
            \\end{figure}
            """)
        end
        write(io, """
        \\begin{verbatim}
        $metrics
        \\end{verbatim}
        \\end{document}
        """)
    end
end